### ISSUE TITLE
难正负样本公式问题

### ISSUE THREAD

**Issue by colinzhaoxp** [bupt-ai-cz/HHCL-ReID#10]
您好，论文中公式(6)(7)采用余弦相似度来挑选难正样本和难负样本，但是为何难正样本是argmax，难负样本是argmin呢？不应该反过来吗？
非常期待您的回复~
![image](https://user-images.githubusercontent.com/48939690/167287869-545db47b-3e3c-46d6-bcc5-ec4a0e8d65af.png)

**Comment by hu-zheng** [comment]
> 您好，论文中公式(6)(7)采用余弦相似度来挑选难正样本和难负样本，但是为何难正样本是argmax，难负样本是argmin呢？不应该反过来吗？ 非常期待您的回复~ ![image](https://user-images.githubusercontent.com/48939690/167287869-545db47b-3e3c-46d6-bcc5-ec4a0e8d65af.png)

非常抱歉，论文中符号确实使用有误，正如你所说这里argmin与argmax使用反了，对于正样本我们希望挑选相似度最小的，而负样本才是挑选相似度最大的。
没有做好勘误的工作是我们的疏忽，我们会尽快纠正错误。非常感谢您的指正~

**Comment by colinzhaoxp** [comment]
谢谢回复，我还以为是自己搞错了呢😄
