### ISSUE TITLE
关于outlier的弃用

### ISSUE THREAD

**Issue by sophieyl820** [bupt-ai-cz/HHCL-ReID#11]
我发现这里训练的时候没有使用到outlier，这样会损失一部分的数据在模型更新上？请问有实验过加outlier的情况吗？

**Comment by hu-zheng** [comment]
Outlier在训练过程中确实是弃用的。可以观察训练过程outlier数量的变化，虽然训练初期outlier会多一点，但是随着训练进行后面epoch重新聚类会减少它们的数量，所以训练终止时实际上并不会有太多样本被弃用。


把这些outlier利用起来确实是可以考虑改进的方向，不过我们在这方面没有做太多探索。


希望对你有所帮助~

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月2日(周四) 上午10:25
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [bupt-ai-cz/HHCL-ReID] 关于outlier的弃用 (Issue #11)




 
我发现这里训练的时候没有使用到outlier，这样会损失一部分的数据在模型更新上？请问有实验过加outlier的情况吗？
