### ISSUE TITLE
hard sample

### ISSUE THREAD

**Issue by gybwyy-art** [bupt-ai-cz/HHCL-ReID#12]
![image](https://user-images.githubusercontent.com/92419787/177126860-5d86576e-893e-4f49-94db-30dbc16a5636.png)
请问这段代码的意思是用hard positive去对当前质心做动量更新吗？这样可以对应论文中的使用hard positive做对比学习吗？那hard negtive如何在代码中体现呢？

**Comment by hu-zheng** [comment]
如你所说，上述CMhybrid代码中不同类对比时的特征并不是严格意义的hard negative

hard instance的使用对应在CMhybrid_v2这部分：https://github.com/bupt-ai-cz/HHCL-ReID/blob/4986b46251dedb6c35b79bf3dfcada75b188f379/hhcl/models/cm.py#L216-L225
