### ISSUE TITLE
ModuleNotFoundError: No module named 'hhcl.datasets.veri'

### ISSUE THREAD

**Issue by ghost** [bupt-ai-cz/HHCL-ReID#13]
(tf1.14) root@dl-220706210722719-pod-jupyter-58b598676f-pfb64:~/HHCL-ReID# CUDA_VISIBLE_DEVICES=0 python examples/train.py -b 256 -a resnet50 -d market1501 --iters 200 --eps 0.45 --momentum 0.1 --num-instances 16 --pooling-type avg --memorybank CMhybrid --epochs 60 --logs-dir examples/logs/market1501/resnet50_avg_cmhybrid
Traceback (most recent call last):
  File "examples/train.py", line 20, in <module>
    from hhcl import datasets
  File "/root/HHCL-ReID/hhcl/__init__.py", line 3, in <module>
    from . import datasets
  File "/root/HHCL-ReID/hhcl/datasets/__init__.py", line 7, in <module>
    from .veri import VeRi
ModuleNotFoundError: No module named 'hhcl.datasets.veri'

**Comment by hu-zheng** [comment]
Dataset veri is not used in our experiment, so Line 7 is redundant. I have fixed this bug. Git pull the latest codebase or comment out this line and it will work.
