### ISSUE TITLE
为什么loss cls和loss ins值是一样的？

### ISSUE THREAD

**Issue by MoEmma** [bupt-ai-cz/HHCL-ReID#14]

**Comment by hu-zheng** [comment]
你好～请问这个iter是第一个吗？因为feature初始话都是使用cluster_feautres，第一个iter memory里特征还没更新，所以一样是正常的。
你可以尝试看看后面几个iter的结果~



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月23日(周五) 上午10:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [bupt-ai-cz/HHCL-ReID] 为什么loss cls和loss ins值是一样的？ (Issue #14)




 
在实验过程中发现文中提出的两个损失的结果是一样的，ctx中存储的hard samples和centroids两部分的值也是一样的，这是为什么呢？

**Comment by MoEmma** [comment]
对的，我也发现了是第一个所以还没更新，所以准备关闭问题啦，感谢回答！
