### ISSUE TITLE
GPU显存

### ISSUE THREAD

**Issue by stu977** [bupt-ai-cz/HHCL-ReID#15]
想问一下您的GPU显存是多少呢

**Comment by hu-zheng** [comment]
当时应该是使用4张12G显存的2080ti



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月9日(周四) 下午3:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [bupt-ai-cz/HHCL-ReID] GPU显存 (Issue #15)




 
想问一下您的GPU显存是多少呢

**Comment by stu977** [comment]
> 当应是使用4张12G内存的2080ti
> [……](#)
> ---原始邮件--- 发件人: ***@***.***> 发送时间: 2023年3月9日(周四)下午3:10 收件人: ***@***.***>; 抄送: ***@***.***>; 主题：[bupt-ai-cz/HHCL-ReID] GPU 显存（[第 15](https://github.com/bupt-ai-cz/HHCL-ReID/issues/15)期） 想问下您的 GPU 显存是多少呢 — 直接回复此邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您订阅了此线程。消息 ID：***@***.***>

好的，谢谢
