### ISSUE TITLE
model下载链接指向SPCL；库中文件缺失

### ISSUE THREAD

**Issue by colinzhaoxp** [bupt-ai-cz/HHCL-ReID#2]
您好，感谢您非常出色的工作！

但是我在复现时遇到一些问题：

1. model下载链接指向错误，指向了SPCL的训练后的模型，难道通用？
2. evaluation_metrics文件夹中缺失ranking.py文件。我使用cluster-contrast-reid中的文件进行替换后可以运行，但不知是否有影响。
3. utils文件夹下缺失serialization.py文件。解决方法同2。

非常期待您的回复，谢谢！

**Comment by hu-zheng** [comment]
抱歉，我们的工作是follow SPCL的，缺失脚本替换不影响。
目前代码已更新，十分感谢您给我们指出错误和问题~

**Comment by colinzhaoxp** [comment]
谢谢您的回复~
