### ISSUE TITLE
关于CMhybrid和CMhybrid_v2两种Memory Bank的理解疑惑

### ISSUE THREAD

**Issue by colinzhaoxp** [bupt-ai-cz/HHCL-ReID#3]
您好，感谢您进一步完善了相关代码。

在复现及阅读代码过程中遇到一些问题，经过一段时间还是有疑惑，在此提问，希望您能抽出宝贵时间来解惑。

在论文4.3节提到，新构建了一个P\*C的instance features memory bank。在代码中，这一部分对应到train.py的206-212行代码，有CMhybrid和CMhybrid_v2两种类型bank。CMhybrid是直接加倍cluster_featuers；CMhybrid_v2则按照论文所说从每个类中随机抽取P个instace feature，相当于在cluster_features基础上新加了P\*C个特征。

按照您提供的训练模型，性能较好的却是采用CMhybrid类型的bank，而CMhybrid没有构建论文4.3节中提出的P\*C的instance feature memory bank.这个核心点。

请问我理解的对吗？

CMhybrid和CMhybrid_v2的区别您认为有何不同呢？

非常期待您的回复！

注：train.py和cm.py文件中，cmhybrid拼写出现了小错误。

**Comment by hu-zheng** [comment]
感谢你的关注~
1. 我们实验也发现了CMhybrid这种只增加一个hard feature并使用动量方式更新，相比于单纯只使用cluster feature就能够直接提升效果；
2. 对于 CMhybrid_v2中使用P*C的instance feature memory bank，其目的是引入更多特征，在mining的时候能够挑选到更有用的hard sample；但是，这样的策略也增加选到噪声样本的风险，使得网络训练不是很稳定，使得hard instance的作用不明显。可以尝试适当调节hard instance loss的权重和它里面的温度系数来改变这部分损失的大小，或者尝试不同P的大小。
其实，后来我也想过我们方法的问题，我们这种hardest的策略并不是最优的，可以结合metric learning里像semi-hard这类soft的mining策略，但是限于时间没有做全面的实验对比。

**Comment by hu-zheng** [comment]
> 您好，感谢您进一步完善了相关代码。
> 
> 在复现及阅读代码过程中遇到一些问题，经过一段时间还是有疑惑，在此提问，希望您能抽出宝贵时间来解惑。
> 
> 在论文4.3节提到，新构建了一个P*C的instance features memory bank。在代码中，这一部分对应到train.py的206-212行代码，有CMhybrid和CMhybrid_v2两种类型bank。CMhybrid是直接加倍cluster_featuers；CMhybrid_v2则按照论文所说从每个类中随机抽取P个instace feature，相当于在cluster_features基础上新加了P*C个特征。
> 
> 按照您提供的训练模型，性能较好的却是采用CMhybrid类型的bank，而CMhybrid没有构建论文4.3节中提出的P*C的instance feature memory bank.这个核心点。
> 
> 请问我理解的对吗？
> 
> CMhybrid和CMhybrid_v2的区别您认为有何不同呢？
> 
> 非常期待您的回复！
> 
> 注：train.py和cm.py文件中，cmhybrid拼写出现了小错误。

感谢你的关注~
1. 我们实验也发现了CMhybrid这种只增加一个hard feature并使用动量方式更新，相比于单纯只使用cluster feature就能够直接提升效果；
2. 对于 CMhybrid_v2中使用P*C的instance feature memory bank，其目的是引入更多特征，在mining的时候能够挑选到更有用的hard sample；但是，这样的策略也增加选到噪声样本的风险，使得网络训练不是很稳定，使得hard instance的作用不明显。可以尝试适当调节hard instance loss的权重和它里面的温度系数来改变这部分损失的大小，或者尝试不同P的大小。
3. 其实，后来我也想过我们方法的问题，我们这种hardest的策略并不是最优的，可以结合metric learning里像semi-hard这类soft的mining策略，但是限于时间没有做全面的实验对比。

**Comment by colinzhaoxp** [comment]
感谢您十分详细的回复~
