### ISSUE TITLE
关于算法最终性能的一些疑问

### ISSUE THREAD

**Issue by chenyiyuu** [bupt-ai-cz/HHCL-ReID#4]
首先感谢您做出的杰出贡献！
最近在我复现您的代码的过程中，我发现我复现的结果和您论文中的结果存在一定的性能差距。我在market1501上不做任何修改使用run.sh中的命令执行，使用CMhybrid memory最终获得的性能是82.4%mAP，和84.2有些差距。请问下您还有使用一些别的技巧或者改进了代码进一步提高了性能？
期待得到您的回复，谢谢！

**Comment by hu-zheng** [comment]
感谢关注~
1. 我们是用4*2080TI的环境实验的，也是按照默认配置训练的结果，并没有使用额外的技巧。
2. 环境差异以及随机性可能对结果有些许影响，这个任务4卡训练和较大的batchsize对结果影响较大。
3. 对于额外的技巧，主页里提到的gem等方都是能够提升效果的，另外有时适当增加训练几个epoch会对mAP有一些收益。
