### ISSUE TITLE
所提供的训练模型在duke上表现mAP：73.2%

### ISSUE THREAD

**Issue by colinzhaoxp** [bupt-ai-cz/HHCL-ReID#5]
完全无监督
![image](https://user-images.githubusercontent.com/48939690/148895896-d5cac955-5467-4e77-8cee-7188045b14da.png)
有监督
![image](https://user-images.githubusercontent.com/48939690/148896489-bbf5ec07-a9d0-4c9b-bc0f-28bd73c15e5f.png)

您好，在使用所提供的训练模型进行测试时，发现性能并没有论文中所提到的精度，是不是上传有错误呢？

**Comment by hu-zheng** [comment]
你好，我也测试了一下自己上传模型，对比论文结果是吻合的。
完全无监督：
![image](https://user-images.githubusercontent.com/35828789/148978972-89aa8709-965f-4012-b596-88d0a58d6b67.png)
有监督：
![image](https://user-images.githubusercontent.com/35828789/148982246-2bf2c5f7-deb2-4c09-b29a-bd3d5a8c7306.png)
你复现出现的这个误差我目前也不能确定是什么原因，不过你测试的结果与论文结果其实已经相差无几了。

**Comment by colinzhaoxp** [comment]
> 你好，我也测试了一下自己上传模型，对比论文结果是吻合的。 完全无监督： ![image](https://user-images.githubusercontent.com/35828789/148978972-89aa8709-965f-4012-b596-88d0a58d6b67.png) 有监督： ![image](https://user-images.githubusercontent.com/35828789/148982246-2bf2c5f7-deb2-4c09-b29a-bd3d5a8c7306.png) 你复现出现的这个误差我目前也不能确定是什么原因，不过你测试的结果与论文结果其实已经相差无几了。

谢谢，第一个完全无监督，我对比论文看成有监督的数据了，我的锅😂
