### ISSUE TITLE
可以汇报一下在MSMT17上的效果吗

### ISSUE THREAD

**Issue by July-zh** [bupt-ai-cz/HHCL-ReID#7]
我自己跑了一下，效果不太好，能解释一下吗？

**Comment by hu-zheng** [comment]
我们方法在MSMT17 上的结果（这个数据集上一些超参数需要调整一下 --iters 300 --eps 0.7 ）：
Mean AP: 31.8%
CMC Scores:
  top-1          58.9%
  top-5          71.3%
  top-10         75.8%

我们的方法在MSMT17取得了和cluster contrast相当的效果，提升没有特别显著；
另外，值得一提的是这个数据集相机信息是比较关键的。对比CAP和ICE这两个方法，可以发现他们额外考虑相机信息在MSMT17这个数据集上会有明显增益。

**Comment by July-zh** [comment]
好的，谢谢

**Comment by July-zh** [comment]
这个效果的backbone是用的IBN-Resnet吗，我用resnet50只跑出mAP 25.8%，超参数已经按照你说的调整过了

**Comment by hu-zheng** [comment]
> 这个效果的backbone是用的IBN-Resnet吗，我用resnet50只跑出mAP 25.8%，超参数已经按照你说的调整过了

上述结果是基于resnet50的效果，对应的模型我上传到了[GoogleDrive](https://drive.google.com/file/d/1WubO_rUOb9kgKeCv6Hx7EBez6l2h8NbB/view?usp=sharing)
相应的训练命令如下：
`CUDA_VISIBLE_DEVICES=0,1,2,3 python examples/train.py -b 256 -a resnet50 -d msmt17 --iters 300 --eps 0.7 --num-instances 16 --pooling-type avg --memorybank CMhybrid --epochs 60 --logs-dir examples/logs/msmt17/resnet50_avg_cmhybrid_iters300`
