### ISSUE TITLE
单卡训练降低10+ pp. 性能

### ISSUE THREAD

**Issue by ttt0666** [bupt-ai-cz/HHCL-ReID#8]
你好，我用一块RTX 24g的卡在market1501数据集上使用命令训练：
```
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python train.py -b 256 -a resnet50 -d market1501 \
--iters 200 --eps 0.45 --num-instances 16 --pooling-type avg --memorybank CMhybrid --epochs 60 \
--logs-dir work_dirs/logs/market1501/resnet50_avg_cmhybrid
```
但得到的结果mAP=71.4,Top-1=85.7，相差10个点以上，请问，单卡训练时有影响性能的情况么？其他的参数有什么需要另外设置的嘛？
谢谢！

**Comment by ttt0666** [comment]
Args:Namespace(arch='resnet50', batch_size=512, data_dir='/tianyanling/data/re-id', dataset='market1501', dropout=0, epochs=60, eps=0.45, eps_gap=0.02, eval_step=10, features=0, hard_weight=0.5, height=256, iters=200, k1=30, k2=6, logs_dir='work_dirs/logs/market1501/resnet50_avg_cmhybrid_gpu2_b512_lrsame', lr=0.00035, memorybank='CMhybrid', momentum=0.1, num_instances=16, pooling_type='avg', print_freq=10, resume='', seed=1, smooth=0, step_size=20, temp=0.05, weight_decay=0.0005, width=128, workers=4)
上面是我训练时的args,请问有哪里不一样嘛？

**Comment by hu-zheng** [comment]
你好，很抱歉我没有基于单卡做过本实验，所以也没有单卡下与多卡结果对齐准确配置，但是我想问题可能是出在BN上。代码中使用的是nn.DataParallel，当 batch_size=256时，如果使用4卡训练，则分配在每个GPU上64张图像数据，每个GPU会分别计算各自的mean和std进行BN。你可以把batch_size设为64，并同时减小学习率（一般说法是等比例缩小，但可能还需要适当调整）。
如果有条件，建议还是使用多卡实验，避免不必要的麻烦~

**Comment by hu-zheng** [comment]
> 

你好，很抱歉我没有基于单卡做过本实验，所以也没有单卡下与多卡结果对齐准确配置，但是我想问题可能是出在BN上。代码中使用的是nn.DataParallel，当 batch_size=256时，如果使用4卡训练，则分配在每个GPU上64张图像数据，每个GPU会分别计算各自的mean和std进行BN。你可以把batch_size设为64，并同时减小学习率（一般说法是等比例缩小，但可能还需要适当调整）。
如果有条件，建议还是使用多卡实验，避免不必要的麻烦~

**Comment by hu-zheng** [comment]
> Args:Namespace(arch='resnet50', batch_size=512, data_dir='/tianyanling/data/re-id', dataset='market1501', dropout=0, epochs=60, eps=0.45, eps_gap=0.02, eval_step=10, features=0, hard_weight=0.5, height=256, iters=200, k1=30, k2=6, logs_dir='work_dirs/logs/market1501/resnet50_avg_cmhybrid_gpu2_b512_lrsame', lr=0.00035, memorybank='CMhybrid', momentum=0.1, num_instances=16, pooling_type='avg', print_freq=10, resume='', seed=1, smooth=0, step_size=20, temp=0.05, weight_decay=0.0005, width=128, workers=4)� 上面是我训练时的args,请问有哪里不一样嘛？

你好，很抱歉我没有基于单卡做过本实验，所以也没有单卡下与多卡结果对齐准确配置，但是我想问题可能是出在BN上。代码中使用的是nn.DataParallel，当 batch_size=256时，如果使用4卡训练，则分配在每个GPU上64张图像数据，每个GPU会分别计算各自的mean和std进行BN。你可以把batch_size设为64，并同时减小学习率（一般说法是等比例缩小，但可能还需要适当调整）。
如果有条件，建议还是使用多卡实验，避免不必要的麻烦~
