### ISSUE TITLE
精度偏低的原因

### ISSUE THREAD

**Issue by MoEmma** [bupt-ai-cz/HHCL-ReID#9]
当我用两个GPU，选择batch_size为128时，在market1501数据集上的map只有75.0，与论文中数据对比降低了10个百分点。请问这个数据合理吗？

**Comment by hu-zheng** [comment]
> 当我用两个GPU，选择batch_size为128时，在market1501数据集上的map只有75.0，与论文中数据对比降低了10个百分点。请问这个数据合理吗？

不好意思，我们只在GPUs=4的设置下进行了实验,如果bs减小其他参数保持不变确实效果可能会有差异。
通常batchsize改变时，iters和lr也需要适当调整。相比于默认4卡训练，如果使用2卡训练，当bs /= 2时， 通常iters *= 2， lr /= 2

**Comment by MoEmma** [comment]
好的，非常感谢您的回答，我会调整看看。
